### ISSUE TITLE
fix feature types

### ISSUE THREAD

**Issue by mboecker** [mlr3learners/mlr3learners.kernlab#1]

**Comment by mboecker** [comment]
@pat-s

is autotest correct and tests all feature types? otherwise we should extend autotests to do that.

**Comment by pat-s** [comment]
Looking into `tasks` from

https://github.com/mlr-org/mlr3/blob/2ceb77be634ae67a25575d387a5f59e5f3f1f003/inst/testthat/helper_autotest.R#L254-L256

shows among others

```
$missings_each_row_multiclass
<TaskClassif:missings_each_row_multiclass> (30 x 7)
* Target: target
* Properties: multiclass
Features (6):
* chr (1): character
* fct (1): factor
* int (1): integer
* lgl (1): logical
* dbl (1): numeric
* ord (1): ordered
```

So I guess yes, it checks all "common" feature types. Once we have special tasks, these should be added to `run_autotests()` tasks. 

I am not aware of any additional feature types?

**Comment by mboecker** [comment]
Yes thanks for pointing me in the right direction. This means we can close this issue.

There are references to a PosixCT feature type but I dont think it's used yet or consistently implemented. Just letting you know in case that got removed and I shouldnt have stumbled over it.
