### ISSUE TITLE
rename this repo to mlr3learner.ksvm

### ISSUE THREAD

**Issue by mboecker** [mlr3learners/mlr3learners.kernlab#10]
can someone with the required permissions please rename this repository to "mlr3learner.ksvm" since thats how all the other repos are named?

@jakob-r

**Comment by jakob-r** [comment]
I think @pat-s has the rights to do that at the moment.

**Comment by pat-s** [comment]
done

**Comment by be-marc** [comment]
@pat-s @mboecker Please change the name to `mlr3learners.ksvm` and rename the github description to `kernlab::ksvm for mlr3`

And can you also do this for mlr3learners/mlr3learner.ctree?

**Comment by pat-s** [comment]
done
