### ISSUE TITLE
find solution for kernel hyper parameters

### ISSUE THREAD

**Issue by mboecker** [mlr3learners/mlr3learners.kernlab#4]

**Comment by pat-s** [comment]
If you mean with this issue how to define dependent parameters of kernel functions, take a look here:

https://github.com/mlr-org/mlr3learners/blob/4a33f50ab91bf721c73c522b4a3f81804f79b9dc/R/LearnerRegrXgboost.R#L71-L81

**Comment by mboecker** [comment]
Thank you, that'll work.

**Comment by mboecker** [comment]
What do you think of my solution?

https://github.com/mboecker/mlr3learner-ksvm/blob/master/R/LearnerClassifKSVM.R#L40

I'm especially unsure about using the "kpar" tag for the hyperparameters. I'm using the predict tag, because I have to use either train or predict and I dont want the hyperparameters in the train parameter set.

**Comment by jakob-r** [comment]
use train as tag and then split them with `setdiff` or something like that

**Comment by jakob-r** [comment]
Also probably delete some kernels (see https://github.com/mlr-org/mlr/issues/739)
