### ISSUE TITLE
tanhdot and splinedot

### ISSUE THREAD

**Issue by mboecker** [mlr3learners/mlr3learners.kernlab#8]
There are some kernels that we dont test in https://github.com/mlr3learners/mlr3learner-ksvm/blob/master/tests/testthat/test_ksvm_kpar.R because they dont work yet. I couldn't figure out what the problem is. Not sure if the problem is on our side. Maybe we could just disable those kernels (tanhdot, splinedot)?

**Comment by pat-s** [comment]
In mlr2 we only test "rbf", "polydot" and "laplacedot". If you cannot get "tanhdot" and "splinedot" to work without much effort, just leave them out entirely and just state this in the README. These are niche kernels anyway and most people won't use them.

**Comment by mboecker** [comment]
> just leave them out entirely and just state this in the README

Will do, thank you!

**Comment by pat-s** [comment]
But it's great that you tested and tried all of them. It's good if our test suite is as complete as possible with not putting too much effort into it. Thanks!
